### ISSUE TITLE
一个古怪的梗

### ISSUE THREAD

**Issue by caijiang** [mingshz/shopping-beauty-manager#1]
本地开发的时候，若本地cookie存在name，则响应/curretManage 会正常，否者报403

本地权限保存在 antd-pro-authority localStorage 。

本地开发/线上分别跑以下2个流程 将产生不同的地方。
* 完成登录
* 手动移除本地所有cookie( 但不移除localStorage)
* 刷新
* 本地开发会顺利抓取到403异常并且清除权限字符串并且强制刷新
* 线上 会继续显示主界面仅仅在控制台打印出错误

https://github.com/mingshz/shopping-beauty-manager/blob/master/src/services/manager.js getCurrent 中。 @chang0022 帮帮忙。

**Comment by chang0022** [comment]
刚瞅到，我查查看。
